CREATE SEQUENCE user_id_seq
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  CACHE 9999;

CREATE OR REPLACE TRIGGER users_trg1
BEFORE INSERT ON users
FOR EACH ROW
BEGIN
SELECT user_id_seq.nextval INTO :new.id FROM dual;
END;

CREATE TABLE "HR"."USERS" 
   (	"ID" NUMBER(10,0), 
	"NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"ACTIVE" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"BLOCKED" VARCHAR2(1 BYTE) DEFAULT 'N', 
	 CONSTRAINT "USERS_PK" PRIMARY KEY ("ID")
	)
	
CREATE UNIQUE INDEX users_idx_1
  ON users (name);
  
ALTER INDEX users_idx_1
  REBUILD COMPUTE STATISTICS;